### ISSUE TITLE
Custom ID

### ISSUE THREAD

**Issue by hendratommy** [Kamva/mgm#14]
Hi,

How to use our own custom ID? I have an unique identifier and instead using it as normal field I would like to set it as `_id` instead if possible, is it possible?

**Comment by mehran-prs** [comment]
Hi, 
Yes, you need to set your own `ID` field in your model instead of using `DefaultModel`.

```
// This is your model
type MyModel struct {
	mgm.DateFields `bson:",inline"`
	ID             string `json:"id" bson:"_id,omitempty"`

        // Define other fields here
	Name           string `json:"name" bson:"name"`
}

func (f *MyModel) PrepareID(id interface{}) (interface{}, error) {
	return id, nil
}

func (f *MyModel) GetID() interface{} {
	return f.ID
}

func (f *MyModel) SetID(id interface{}) {
	f.ID = id.(string)
}
```

__Note:__  MongoDB by default generates a new `ObjectID` when you do not provide the `_id` field, while your defined type of `ID` field is a string, so be careful and set `_id` field before saving the model, otherwise you will have a `ObjectID` as `_id` value.
