### ISSUE TITLE
How to use relationship 

### ISSUE THREAD

**Issue by vipinblue** [Kamva/mgm#18]
**Describe the bug**
I'm trying to fetch user and his/her profile in a single query, 
how can I  do 
[https://docs.mongodb.com/manual/tutorial/model-embedded-one-to-one-relationships-between-documents/](https://docs.mongodb.com/manual/tutorial/model-embedded-one-to-one-relationships-between-documents/)

**Comment by mehran-prs** [comment]
We do not support relationships by specific methods(because this package is a wrapper of Mongo Go Driver), you can use pipelines or just use two queries to fetch relations something like a method on the first collection.   
e.g., If `User` model has a `Profile` model,so you can define `profile()` method on the `User` model and call it to fetch the profile.
