### ISSUE TITLE
Multiple database

### ISSUE THREAD

**Issue by nilpntr** [Kamva/mgm#31]
Is it possible to add a hook where you can set a database for a model to allow multiple databases?

**Comment by mehran-prs** [comment]
Hi @nilpntr 
Yes, Customize your model by implementing `CollectionGetter` interface:

```go
func (model *Book) Collection() *mgm.Collection {
    // Get default connection client
   _,client,_, err := mgm.DefaultConfigs()

   if err != nil {
      panic(err)
   }

   db := client.Database("another_db")
   return mgm.NewCollection(db, "my_collection")
}
```


Now everywhere you need to get the collection, you should call the `mgm.Coll(&Book{})` method.

__Note:__ You should not get collection by `mgm. CollectionByName` because it returns a new collection using your default connection and default DB.
