### ISSUE TITLE
Mock package

### ISSUE THREAD

**Issue by joshmsamuels** [Kamva/mgm#4]
I am loving mgm! I am also willing to help contribute to make it better.

I think adding a mock package to make mocking the DB easier would be a great improvement to this project

**Comment by joshmsamuels** [comment]
@mehran-prs what do you think about this addition? I would be willing to help/write it I just wouldnt want to waste my time if it wouldnt get accepted

**Comment by mehran-prs** [comment]
@joshmsamuels it will be great, so yes, please go ahead. Thank you for your contribution!

**Comment by joshmsamuels** [comment]
I was looking into this and I think we may need to expose the mongodb connection as a nullable Parma (null would behave exactly as it does now). 

@mehran-prs what do you think about that?

**Comment by mehran-prs** [comment]
Could you explain how it should be used?
@joshmsamuels I'm using repository and dependency injection to mock my DB calls, I think you like [something like this](https://stackoverflow.com/questions/56772452/mocking-mongodb-response-in-go)

**Comment by joshmsamuels** [comment]
Is your mocking usage public? Maybe its just because im not as well-versed in this codebase as you are (duh - its your repo 😂) but I cannot find how to mock the DB instance since its encapsulated out of _my_ structs and methods since its only used internally by mgm.

**Comment by mehran-prs** [comment]
My mocking usage is not public. using the dependency injection pattern is very simple
- define repository interface (an interface that contains methods that need by you to fetch or put data to the database)
- implement this interface in a struct (internally use mgm)
- now you have a repository that does what you want, and you can implement a mock of it, in tests provide your mock to your business logic instead of the actual implementation.

Note that this design is good for something like a clean architecture design pattern.
[see this](https://medium.com/@manakuro/clean-architecture-with-go-bce409427d31)

But if you don't want to use any repository interface and just want to bind your model to mgm, so yes you need to a mock for mgm package.

**Comment by joshmsamuels** [comment]
Thats a good way to be able to mock a database, however, for the small project I am creating it adds a lot of overhead that I dont think is super necessary.

I was looking at [go-sqlmock](https://github.com/DATA-DOG/go-sqlmock) as an example to simplify the mocking without needing an extra abstraction layer and dependency injection

**Comment by mehran-prs** [comment]
We can change the **config** type of mgm to an interface, and then on call to  `mgm.Coll` function we call to the config to returns a new instance of collection **interface**, this can be good, but the problem is the mongo-go-driver. It defined everything as structs, If we define our collection as an interface, we need to define all of the mongo-go-driver collection methods manually in our interface and also track the mongo-go-driver updates to its collection methods.

another way is defining a test database, on each test assert data in that database, and also define the setup, teardown functions and using in each test, clean up everything in the test database (If your project is small, I suggest this way because of time)
something like this:
```go
func TestCreateUser(t testing.T){
    setup()
    defer teardown()
  
    // call to some method to insert data into the database.
   // asset inserted data is what you wanted

}
```

**Comment by joshmsamuels** [comment]
I just didnt want to have to depend on a database at all for the unit tests. If you think it would require more overhead than its worth to expose the database connection I _can_ just close this issue and do the dependency injection

**Comment by mehran-prs** [comment]
mongo-go-driver make very overhead for writing mock page. it has Client(15 methods, main usage is running transactions), Database(14 methods,main usage return a new instance of collection, manage DB,...), Collection(26 methods) , so yes, I think it would require more overhead than its worth to expose a mock package.

 If your mind running tests in CI of your project, injecting DB to CI is possible without the overhead.

I like mock packages for mgm, but mongo-go-driver makes it hard.

**Comment by joshmsamuels** [comment]
Ok thanks. I’m closing this for now but keep it at the back of my head in case I find a good way to do it

**Comment by andy-vm** [comment]
hi @mehran-prs when I try to embed mongo-go-driver mock below into mgm, it failed because mgm always try to create DB client even I use `CreateClient(false)`, maybe it's time to have mock client in mgm to make mock test easier 

https://github.com/mongodb/mongo-go-driver/tree/master/mongo/integration/mtest

```go
mt := mtest.New(t, mtest.NewOptions().ClientType(mtest.Mock).CreateClient(false).Topologies(mtest.Single))
defer mt.Close()
```
